export const cards = [
  { card: 'the magician', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/magician/' },
  { card: 'the high priestess', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/high-priestess/' },
  { card: 'the empress', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/empress/' },
  { card: 'the emperor', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/emperor/' },
  { card: 'the hierophant', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/hierophant/' },
  { card: 'the lovers', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/lovers/' },
  { card: 'the chariot', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/chariot/' },
  { card: 'strength', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/strength/' },
  { card: 'the hermit', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/hermit/' },
  { card: 'wheel of fortune', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/wheel-of-fortune/' },
  { card: 'justice', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/justice/' },
  { card: 'the hanged man', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/hanged-man/' },
  { card: 'death', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/death/' },
  { card: 'temperance', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/temperance/' },
  { card: 'the devil', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/devil/' },
  { card: 'the tower', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/tower/' },
  { card: 'the star', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/star/' },
  { card: 'the moon', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/moon/' },
  { card: 'the sun', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/sun/' },
  { card: 'judgement', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/judgement/' },
  { card: 'the world', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/magician/' },
  { card: 'the fool', link: 'https://www.biddytarot.com/tarot-card-meanings/major-arcana/fool/' },
  { card: 'the ace of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/ace-of-swords/' },
  { card: 'the two of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/two-of-swords/' },
  { card: 'the three of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/three-of-swords/' },
  { card: 'the four of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/four-of-swords/' },
  { card: 'the five of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/five-of-swords/' },
  { card: 'the six of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/six-of-swords/' },
  { card: 'the seven of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/seven-of-swords/' },
  { card: 'the eight of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/eight-of-swords/' },
  { card: 'the nine of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/nine-of-swords/' },
  { card: 'the ten of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/ten-of-swords/' },
  { card: 'the page of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/page-of-swords/' },
  { card: 'the knight of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/knight-of-swords/' },
  { card: 'the king of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/king-of-swords/' },
  { card: 'the queen of swords', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-swords/queen-of-swords/' },
  { card: 'the ace of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/ace-of-cups/' },
  { card: 'the two of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/two-of-cups/' },
  { card: 'the three of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/three-of-cups/' },
  { card: 'the four of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/four-of-cups/' },
  { card: 'the five of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/five-of-cups/' },
  { card: 'the six of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/six-of-cups/' },
  { card: 'the seven of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/seven-of-cups/' },
  { card: 'the eight of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/eight-of-cups/' },
  { card: 'the nine of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/nine-of-cups/' },
  { card: 'the ten of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/ten-of-cups/' },
  { card: 'the page of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/page-of-cups/' },
  { card: 'the knight of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/knight-of-cups/' },
  { card: 'the king of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/king-of-cups/' },
  { card: 'the queen of cups', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-cups/queen-of-cups/' },
  { card: 'the ace of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/ace-of-pentacles/' },
  { card: 'the two of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/two-of-pentacles/' },
  { card: 'the three of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/three-of-pentacles/' },
  { card: 'the four of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/four-of-pentacles/' },
  { card: 'the five of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/five-of-pentacles/' },
  { card: 'the six of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/six-of-pentacles/' },
  { card: 'the seven of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/seven-of-pentacles/' },
  { card: 'the eight of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/eight-of-pentacles/' },
  { card: 'the nine of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/nine-of-pentacles/' },
  { card: 'the ten of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/ten-of-pentacles/' },
  { card: 'the page of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/page-of-pentacles/' },
  { card: 'the knight of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/knight-of-pentacles/' },
  { card: 'the king of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/king-of-pentacles/' },
  { card: 'the queen of pentacles', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-pentacles/queen-of-pentacles/' },
  { card: 'the ace of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/ace-of-wands/' },
  { card: 'the two of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/two-of-wands/' },
  { card: 'the three of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/three-of-wands/' },
  { card: 'the four of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/four-of-wands/' },
  { card: 'the five of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/five-of-wands/' },
  { card: 'the six of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/six-of-wands/' },
  { card: 'the seven of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/seven-of-wands/' },
  { card: 'the eight of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/eight-of-wands/' },
  { card: 'the nine of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/nine-of-wands/' },
  { card: 'the ten of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/ten-of-wands/' },
  { card: 'the page of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/page-of-wands/' },
  { card: 'the knight of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/knight-of-wands/' },
  { card: 'the king of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/king-of-wands/' },
  { card: 'the queen of wands', link: 'https://www.biddytarot.com/tarot-card-meanings/minor-arcana/suit-of-wands/queen-of-wands/' }
]